permalink:           /:categories/:year/:month/:day/:title/


title: Jorge Eduardo' Blog
email: jeduoliveira81@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jeduoliveira.github.io" 
twitter_username: jeduoliveira
github_username:  jeduoliveira
paginate:            5

# Build settings
markdown: redcarpet
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed

# Plugins, Tags, Categories and Analytics  
plugins:          [jekyll-paginate]

version:             1.0.0
