permalink: pretty

title: Jorge Eduardo' Blog
email: jeduoliveira81@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Arquiteto de Soluções, flamenguista, pai da Duda, apaixonado por samba.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" 
twitter_username: jeduoliveira
github_username:  jeduoliveira
paginate:            5

# Build settings
markdown: redcarpet
highlighter: rouge
theme: minima

# Plugins, Tags, Categories and Analytics  
plugins:
  - jekyll-feed
  - jekyll-paginate

version: 1.0.0
